name: rishta_biodata_maker
description: "Create beautiful rishta biodata cards easily."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image
  image_picker: ^1.1.2

  # Export & Share
  path_provider: ^2.1.5
  share_plus: ^10.1.4

  # Ads
  google_mobile_ads: ^5.3.0

  # Permissions
  permission_handler: ^11.3.1

  # Onboarding
  introduction_screen: ^3.1.14

  # Splash
  flutter_native_splash: ^2.4.3

  # Navigation
  go_router: ^14.6.3

  # Misc
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  riverpod_generator: 2.4.0
  riverpod_annotation: 2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/templates/
    - assets/fonts/

  fonts:
    - family: JameelNoori
      fonts:
        - asset: assets/fonts/JameelNooriNastaleeq.ttf